import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { LOAN_SCHEMES } from '../../constants/loanProducts';

declare module 'jspdf' {
  interface jsPDF {
    autoTable: (options: any) => jsPDF;
    lastAutoTable: { finalY: number };
  }
}

export const generateReport = (company: any, scoreData: any, emissions: any) => {
  console.log('Generating PDF for:', company?.name, scoreData?.financial_year);
  try {
    const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  
  const COLORS = {
    primary: [16, 185, 129] as [number, number, number],      // emerald green
    dark: [15, 23, 42] as [number, number, number],           // slate-900
    mid: [30, 41, 59] as [number, number, number],            // slate-800
    light: [241, 245, 249] as [number, number, number],       // slate-100
    muted: [100, 116, 139] as [number, number, number],       // slate-500
  };

  const TABLE_THEME = {
    theme: 'grid' as const,
    headStyles: { fillColor: COLORS.primary, textColor: 255, fontStyle: 'bold' as const, halign: 'center' as const, valign: 'middle' as const },
    bodyStyles: { textColor: 50, cellPadding: 4, valign: 'middle' as const },
    alternateRowStyles: { fillColor: [248, 250, 252] as [number, number, number] },
    margin: { left: 15, right: 15 }
  };

  const addSectionTitle = (title: string, yPos: number) => {
    doc.setTextColor(COLORS.dark[0], COLORS.dark[1], COLORS.dark[2]);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text(title, 15, yPos);
    doc.setFont('helvetica', 'normal');
  };

  const addSubTitle = (title: string, yPos: number) => {
    doc.setTextColor(COLORS.dark[0], COLORS.dark[1], COLORS.dark[2]);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(title, 15, yPos);
    doc.setFont('helvetica', 'normal');
  };

  const drawHeaderAndFooter = (pageTitle: string) => {
    doc.setFillColor(COLORS.primary[0], COLORS.primary[1], COLORS.primary[2]);
    doc.rect(0, 0, 210, 15, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('GREENSCORE', 15, 10);
    doc.setFont('helvetica', 'normal');
    doc.text(pageTitle, 195, 10, { align: 'right' });

    const pageCount = (doc.internal as any).getNumberOfPages();
    doc.setFillColor(COLORS.dark[0], COLORS.dark[1], COLORS.dark[2]);
    doc.rect(0, 285, 210, 12, 'F');
    doc.setTextColor(COLORS.muted[0], COLORS.muted[1], COLORS.muted[2]);
    doc.setFontSize(8);
    doc.text(`Generated by GreenScore Platform - ${company.name} - Page ${pageCount}`, 105, 292, { align: 'center' });
  };

  // --- PAGE 1: COVER PAGE ---
  doc.setFillColor(COLORS.dark[0], COLORS.dark[1], COLORS.dark[2]);
  doc.rect(0, 0, 210, 297, 'F');
  
  doc.setFillColor(COLORS.primary[0], COLORS.primary[1], COLORS.primary[2]);
  doc.rect(0, 40, 210, 2, 'F');
  doc.rect(0, 255, 210, 2, 'F');
  
  doc.setTextColor(COLORS.primary[0], COLORS.primary[1], COLORS.primary[2]);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('GREENSCORE', 20, 30);
  
  doc.setTextColor(COLORS.light[0], COLORS.light[1], COLORS.light[2]);
  doc.setFontSize(22);
  doc.text('ENVIRONMENTAL PERFORMANCE', 20, 70);
  doc.text('REPORT & GREEN CREDIT', 20, 82);
  doc.text('ASSESSMENT', 20, 94);
  
  doc.setFillColor(COLORS.mid[0], COLORS.mid[1], COLORS.mid[2]);
  doc.roundedRect(15, 110, 180, 80, 3, 3, 'F');
  
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(COLORS.light[0], COLORS.light[1], COLORS.light[2]);
  doc.text('Company Details', 25, 122);
  
  doc.setFont('helvetica', 'normal');
  doc.text(`Company:      ${company.name}`, 25, 135);
  doc.text(`GSTIN:        ${company.gstin || 'Not Provided'}`, 25, 145);
  doc.text(`Sector:       ${company.sector}`, 25, 155);
  doc.text(`Revenue:      INR ${company.annual_revenue_cr} Crore`, 25, 165);
  doc.text(`Location:     ${company.city || 'N/A'}, ${company.state || 'N/A'}`, 25, 175);
  
  doc.setTextColor(COLORS.muted[0], COLORS.muted[1], COLORS.muted[2]);
  doc.text(`Report Date:    ${new Date().toLocaleDateString('en-IN')}`, 25, 215);
  doc.text(`Financial Year: ${scoreData.financial_year}`, 25, 225);
  doc.text(`Generated by:   GreenScore Platform`, 25, 235);
  
  doc.setFontSize(9);
  doc.text('This report is based on self-reported data submitted by the company.', 20, 265);
  doc.text('Scores are calculated using BRSR P6 Essential Indicators and GHG Protocol standards.', 20, 271);
  doc.text('References: SEBI BRSR Circular (May 2021) | GHG Protocol Corporate Standard', 20, 277);

  // --- PAGE 2: EXECUTIVE SUMMARY ---
  doc.addPage();
  drawHeaderAndFooter('EXECUTIVE SUMMARY');
  
  addSectionTitle('EXECUTIVE SUMMARY', 30);
  
  autoTable(doc, {
    ...TABLE_THEME,
    startY: 40,
    head: [['Field', 'Value']],
    body: [
      ['GreenScore', `${Number(scoreData.total_score).toFixed(1)} / 100`],
      ['Score Tier', scoreData.score_tier],
      ['Sector Percentile', `Top ${Math.max(1, 100 - Number(scoreData.sector_percentile))}% of ${company.sector}`],
      ['Benchmark Score', `${Number(scoreData.sector_benchmark_score).toFixed(1)} (sector average)`]
    ]
  });

  addSubTitle('Carbon Footprint Summary', doc.lastAutoTable.finalY + 20);
  
  autoTable(doc, {
    ...TABLE_THEME,
    startY: doc.lastAutoTable.finalY + 25,
    head: [['Emission Source', 'Unit', 'Your Intensity']],
    body: [
      ['Total CO2e (Scope 1+2)', 'kgCO2e/INR cr', ((Number(emissions.total_co2e_scope1) + Number(emissions.total_co2e_scope2)) * 1000 / company.annual_revenue_cr).toFixed(2)],
      ['Electricity (Scope 2)', 'kgCO2e/INR cr', (Number(emissions.total_co2e_scope2) * 1000 / company.annual_revenue_cr).toFixed(2)],
      ['Diesel/Other (Scope 1)', 'kgCO2e/INR cr', (Number(emissions.total_co2e_scope1) * 1000 / company.annual_revenue_cr).toFixed(2)]
    ]
  });

  // --- PAGE 3: DETAILED SCORE BREAKDOWN ---
  doc.addPage();
  drawHeaderAndFooter('SCORE BREAKDOWN');
  
  addSectionTitle('GREEN CREDIT SCORE BREAKDOWN', 30);
  
  autoTable(doc, {
    ...TABLE_THEME,
    startY: 40,
    head: [['Pillar', 'Weight', 'Your Score', 'Max', 'Contribution']],
    body: [
      ['Energy & Carbon', '40%', Number(scoreData.energy_score).toFixed(1), '100', (Number(scoreData.energy_score) * 0.4).toFixed(1)],
      ['Water Management', '20%', Number(scoreData.water_score).toFixed(1), '100', (Number(scoreData.water_score) * 0.2).toFixed(1)],
      ['Waste Management', '20%', Number(scoreData.waste_score).toFixed(1), '100', (Number(scoreData.waste_score) * 0.2).toFixed(1)],
      ['Renewable Energy', '10%', Number(scoreData.renewables_score).toFixed(1), '100', (Number(scoreData.renewables_score) * 0.1).toFixed(1)],
      ['Governance', '10%', Number(scoreData.governance_score).toFixed(1), '100', (Number(scoreData.governance_score) * 0.1).toFixed(1)],
      ['TOTAL', '100%', Number(scoreData.total_score).toFixed(1), '100', Number(scoreData.total_score).toFixed(1)]
    ],
    foot: [['TOTAL', '100%', '-', '100', Number(scoreData.total_score).toFixed(1)]],
    footStyles: { fillColor: COLORS.mid, textColor: 255, fontStyle: 'bold' as const, halign: 'center' as const }
  });
  
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  const methodologyText = "Methodology: Scores are intensity-based (per INR crore revenue) to ensure fairness across company sizes. The formula uses an exponential decay curve where an average sector intensity yields a score of 50. Lower emissions and higher resource efficiency yield scores approaching 100.";
  doc.text(doc.splitTextToSize(methodologyText, 180), 15, doc.lastAutoTable.finalY + 15);

  // --- PAGE 4: EMISSIONS DETAIL ---
  doc.addPage();
  drawHeaderAndFooter('EMISSIONS INVENTORY');
  
  addSectionTitle(`EMISSIONS INVENTORY - FY ${scoreData.financial_year}`, 30);
  
  addSubTitle('Scope 1 - Direct Emissions', 45);
  autoTable(doc, {
    ...TABLE_THEME,
    startY: 50,
    head: [['Source', 'Reported Intensity', 'CO2e (tonnes)']],
    body: [
      ['Diesel', `${Number(emissions.diesel_litres_per_cr).toFixed(1)} L/INR cr`, Number(emissions.total_co2e_scope1).toFixed(2)],
      ['LPG', `${Number(emissions.lpg_kg_per_cr).toFixed(1)} kg/INR cr`, '-']
    ]
  });
  
  addSubTitle('Scope 2 - Indirect Emissions', doc.lastAutoTable.finalY + 15);
  autoTable(doc, {
    ...TABLE_THEME,
    startY: doc.lastAutoTable.finalY + 20,
    head: [['Source', 'Reported Intensity', 'CO2e (tonnes)']],
    body: [
      ['Electricity', `${Number(emissions.electricity_mwh_per_cr).toFixed(2)} MWh/INR cr`, Number(emissions.total_co2e_scope2).toFixed(2)]
    ]
  });

  const totalCO2e = Number(emissions.total_co2e_scope1) + Number(emissions.total_co2e_scope2);
  const intensity = (totalCO2e * 1000) / company.annual_revenue_cr;
  
  doc.setTextColor(COLORS.primary[0], COLORS.primary[1], COLORS.primary[2]);
  doc.setFont('helvetica', 'bold');
  doc.text(`Total GHG Emissions: ${totalCO2e.toFixed(2)} tCO2e`, 15, doc.lastAutoTable.finalY + 20);
  doc.text(`Intensity: ${intensity.toFixed(2)} kgCO2e per INR crore revenue`, 15, doc.lastAutoTable.finalY + 28);
  doc.setFont('helvetica', 'normal');

  // --- PAGE 5: WATER & WASTE ---
  doc.addPage();
  drawHeaderAndFooter('WATER & WASTE');
  
  addSectionTitle('WATER AND WASTE MANAGEMENT', 30);
  
  addSubTitle('Water Management', 45);
  autoTable(doc, {
    ...TABLE_THEME,
    startY: 50,
    head: [['Metric', 'Your Value', 'Unit']],
    body: [
      ['Water Withdrawal', Number(emissions.water_withdrawal_kl_per_cr).toFixed(1), 'KL/INR cr'],
      ['Water Recycled', `${Number(emissions.water_recycled_pct).toFixed(1)}%`, '% of total'],
      ['Wastewater Treated', `${Number(emissions.wastewater_treated_pct).toFixed(1)}%`, '% before discharge']
    ]
  });
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text('BRSR Reference: Principle 6 Essential Indicator C - Water withdrawal and consumption.', 15, doc.lastAutoTable.finalY + 8);
  
  addSubTitle('Waste Management', doc.lastAutoTable.finalY + 20);
  autoTable(doc, {
    ...TABLE_THEME,
    startY: doc.lastAutoTable.finalY + 25,
    head: [['Metric', 'Your Value', 'Unit']],
    body: [
      ['Waste Generated', Number(emissions.waste_generated_t_per_cr).toFixed(2), 'tonnes/INR cr'],
      ['Hazardous Waste', `${Number(emissions.hazardous_waste_pct).toFixed(1)}%`, '% of total'],
      ['Waste Recycled', `${Number(emissions.waste_recycled_pct).toFixed(1)}%`, '% of total']
    ]
  });
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text('BRSR Reference: Principle 6 Essential Indicator D - Waste generated and managed.', 15, doc.lastAutoTable.finalY + 8);

  // --- PAGE 6: LOAN ELIGIBILITY ---
  doc.addPage();
  drawHeaderAndFooter('LOAN ELIGIBILITY');
  
  addSectionTitle('GREEN LOAN ELIGIBILITY ASSESSMENT', 30);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const loanIntro = `Based on your GreenScore of ${Number(scoreData.total_score).toFixed(1)}/100, you are eligible for the following green financing products. Rates shown are preferential green rates compared to standard SME loan rates of approximately 14% p.a.`;
  doc.setTextColor(50, 50, 50);
  doc.text(doc.splitTextToSize(loanIntro, 180), 15, 40);
  
  const eligibleLoans = LOAN_SCHEMES.filter(l => Number(scoreData.total_score) >= l.minScore && (!l.eligibleSectors || l.eligibleSectors.includes(company.sector)));
  const loanTableBody = eligibleLoans.map(l => [
    l.bank, l.scheme, l.minScore.toString(), `${l.rateMin}-${l.rateMax}%`, `INR ${l.maxAmountCr} Cr`, `${l.tenureYears} yr`
  ]);
  
  autoTable(doc, {
    ...TABLE_THEME,
    startY: 55,
    head: [['Bank', 'Scheme', 'Min Score', 'Rate (p.a.)', 'Max Amount', 'Tenure']],
    body: loanTableBody.length > 0 ? loanTableBody : [['No eligible loans currently', '-', '-', '-', '-', '-']]
  });

  if (eligibleLoans.length > 0) {
    const bestRate = Math.min(...eligibleLoans.map(l => l.rateMin));
    addSubTitle('Potential Savings (sample INR 50 Lakh loan):', doc.lastAutoTable.finalY + 15);
    
    autoTable(doc, {
      ...TABLE_THEME,
      startY: doc.lastAutoTable.finalY + 20,
      head: [['Rate', 'Annual Interest', '7-Year Total', 'Saving vs 14%']],
      body: [
        ['14% (standard)', 'INR 7,00,000', 'INR 49,00,000', '-'],
        [`${bestRate}% (Best Eligible)`, `INR ${(5000000 * bestRate / 100).toLocaleString('en-IN')}`, `INR ${(5000000 * bestRate / 100 * 7).toLocaleString('en-IN')}`, `INR ${(4900000 - (5000000 * bestRate / 100 * 7)).toLocaleString('en-IN')}`]
      ]
    });
  }

  // --- PAGE 7: IMPROVEMENT ROADMAP ---
  doc.addPage();
  drawHeaderAndFooter('IMPROVEMENT ROADMAP');
  
  addSectionTitle('RECOMMENDED IMPROVEMENT ROADMAP', 30);
  addSubTitle('12-Month Action Plan:', 45);
  
  autoTable(doc, {
    ...TABLE_THEME,
    startY: 50,
    head: [['Priority', 'Area', 'Action', 'Expected Impact']],
    body: [
      ['1', 'Renewables', 'Install rooftop solar (MNRE subsidy available)', '+8 to +12 pts'],
      ['2', 'Governance', 'Publish environmental policy + set targets', '+6 to +10 pts'],
      ['3', 'Waste', 'Increase recycling via certified vendor', '+3 to +5 pts'],
      ['4', 'Water', 'Install water meters + closed-loop cooling', '+2 to +4 pts']
    ]
  });
  
  doc.setTextColor(COLORS.primary[0], COLORS.primary[1], COLORS.primary[2]);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text(`Projected Score in 12 Months: ${Math.min(100, Math.floor(Number(scoreData.total_score) + 15))} - ${Math.min(100, Math.floor(Number(scoreData.total_score) + 25))} / 100`, 15, doc.lastAutoTable.finalY + 20);
  doc.setFont('helvetica', 'normal');

  // --- PAGE 8: REGULATORY CONTEXT ---
  doc.addPage();
  drawHeaderAndFooter('REGULATORY CONTEXT');
  
  addSectionTitle('REGULATORY FRAMEWORK & REFERENCES', 30);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(50, 50, 50);
  const refText = `This report references the following regulatory frameworks and standards:

1. SEBI BRSR Circular (May 2021) - Business Responsibility and Sustainability Reporting framework mandated for top 1,000 listed Indian companies. GreenScore uses BRSR Principle 6 (Environment) Essential Indicators as the scoring backbone.

2. GHG Protocol Corporate Standard - World's most widely used greenhouse gas accounting standard. All emission calculations in this report follow GHG Protocol Scope 1 and Scope 2 methodology.

3. CEA India Grid Emission Factor (2023) - Central Electricity Authority of India's annual national grid emission factor of 0.71 kgCO2e/kWh used for Scope 2 calculations.

4. RBI Green Finance Taxonomy (2023) - Reserve Bank of India's framework for green lending. Loan eligibility in this report is aligned with RBI PSL (Priority Sector Lending) green categories.

5. Bureau of Energy Efficiency (BEE) - Indian sector energy benchmarks sourced from BEE's Perform Achieve Trade (PAT) scheme data.`;

  doc.text(doc.splitTextToSize(refText, 180), 15, 45);
  
  doc.setFillColor(COLORS.light[0], COLORS.light[1], COLORS.light[2]);
  doc.rect(15, 170, 180, 40, 'F');
  doc.setTextColor(COLORS.dark[0], COLORS.dark[1], COLORS.dark[2]);
  doc.setFont('helvetica', 'bold');
  doc.text('Disclaimer:', 20, 180);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(80, 80, 80);
  const disclaimer = `This report is generated based on self-reported data. GreenScore does not independently verify submitted data. Scores are indicative and should not be used as the sole basis for financial decisions. Emission factors and sector benchmarks are updated annually. This report is valid for FY ${scoreData.financial_year} only.`;
  doc.text(doc.splitTextToSize(disclaimer, 170), 20, 188);
  
  // SAVE PDF
  doc.save(`GreenScore_Report_${(company.name || 'Company').replace(/\s+/g, '_')}_FY${scoreData.financial_year || '2023'}.pdf`);
  } catch (error) {
    console.error('PDF Generation Failed:', error);
  }
};
