export interface LoanScheme {
  id: string;
  bank: string;
  bankLogo: string;
  scheme: string;
  minScore: number;
  min_score: number;
  maxAmountCr: number;
  max_amount_cr: number;
  rateMin: number;
  rate_min: number;
  rateMax: number;
  rate_max: number;
  tenureYears: number;
  tenure_yr: number;
  eligibleSectors: string[] | null;
  eligible_sectors: string[] | null;
  tag: string;
  tagColour: string;
  highlight: string;
  description: string;
  requirements: string[];
  applyUrl: string;
  apply_url: string;
  infoUrl: string;
  info_url: string;
  sourceLabel: string;
}

export const LOAN_SCHEMES: LoanScheme[] = [
  {
    id: "sidbi-gfs",
    bank: "SIDBI",
    bankLogo: "🏦",
    scheme: "Green Finance Scheme (GFS)",
    minScore: 55,
    min_score: 55,
    maxAmountCr: 5,
    max_amount_cr: 5,
    rateMin: 8.0,
    rate_min: 8.0,
    rateMax: 9.5,
    rate_max: 9.5,
    tenureYears: 7,
    tenure_yr: 7,
    eligibleSectors: null,
    eligible_sectors: null,
    tag: "RBI Priority Sector",
    tagColour: "emerald",
    highlight: "Concessional green funding",
    description: "Financing for renewable energy, energy efficiency, EVs, waste management, green manufacturing",
    requirements: [
      "GreenScore ≥ 55",
      "All sectors eligible",
      "Audited financials for 2 years",
      "MSME registration (Udyam)"
    ],
    applyUrl: "https://onlineloanappl.sidbi.in/OnlineApplication/",
    apply_url: "https://onlineloanappl.sidbi.in/OnlineApplication/",
    infoUrl: "https://www.sidbi.in/en/green-finance",
    info_url: "https://www.sidbi.in/en/green-finance",
    sourceLabel: "SIDBI Official Green Finance Page",
  },
  {
    id: "sidbi-4e",
    bank: "SIDBI",
    bankLogo: "⚡",
    scheme: "4E Scheme (End-to-End Energy Efficiency)",
    minScore: 55,
    min_score: 55,
    maxAmountCr: 3,
    max_amount_cr: 3,
    rateMin: 7.5,
    rate_min: 7.5,
    rateMax: 9.0,
    rate_max: 9.0,
    tenureYears: 5,
    tenure_yr: 5,
    eligibleSectors: ["Textile & Apparel", "Auto Parts", "Chemical", "Food Processing"],
    eligible_sectors: ["Textile & Apparel", "Auto Parts", "Chemical", "Food Processing"],
    tag: "Energy Efficiency",
    tagColour: "yellow",
    highlight: "MSME energy-efficiency upgrades",
    description: "MSME energy-efficiency machinery upgrades and sustainable equipment financing",
    requirements: [
      "GreenScore ≥ 55",
      "Sectors: Textile, Auto Parts, Chemical, Food Processing",
      "BEE certified energy audit required",
      "Udyam registration mandatory"
    ],
    applyUrl: "https://onlineloanappl.sidbi.in/OnlineApplication/",
    apply_url: "https://onlineloanappl.sidbi.in/OnlineApplication/",
    infoUrl: "https://www.sidbi.in/en/green-finance",
    info_url: "https://www.sidbi.in/en/green-finance",
    sourceLabel: "SIDBI Official Green Finance Page",
  },
  {
    id: "sidbi-mse-gift",
    bank: "SIDBI",
    bankLogo: "🌱",
    scheme: "MSE-GIFT Scheme",
    minScore: 50,
    min_score: 50,
    maxAmountCr: 2,
    max_amount_cr: 2,
    rateMin: 7.0,
    rate_min: 7.0,
    rateMax: 8.5,
    rate_max: 8.5,
    tenureYears: 5,
    tenure_yr: 5,
    eligibleSectors: null,
    eligible_sectors: null,
    tag: "World Bank RAMP",
    tagColour: "emerald",
    highlight: "Concessional green technology adoption",
    description: "Concessional green technology adoption financing for MSMEs under World Bank RAMP Programme",
    requirements: [
      "GreenScore ≥ 50",
      "All sectors eligible",
      "Eligible for World Bank RAMP benefits",
      "Saves up to 1.5% interest rates"
    ],
    applyUrl: "https://onlineloanappl.sidbi.in/OnlineApplication/",
    apply_url: "https://onlineloanappl.sidbi.in/OnlineApplication/",
    infoUrl: "https://www.sidbi.in/en/pages/incentive-schemes-for-green-loans",
    info_url: "https://www.sidbi.in/en/pages/incentive-schemes-for-green-loans",
    sourceLabel: "SIDBI Green Loan Incentives Page",
  },
  {
    id: "sidbi-mse-spice",
    bank: "SIDBI",
    bankLogo: "🔄",
    scheme: "MSE-SPICE Scheme",
    minScore: 55,
    min_score: 55,
    maxAmountCr: 2,
    max_amount_cr: 2,
    rateMin: 7.5,
    rate_min: 7.5,
    rateMax: 9.0,
    rate_max: 9.0,
    tenureYears: 5,
    tenure_yr: 5,
    eligibleSectors: ["Chemical", "Food Processing", "Textile & Apparel"],
    eligible_sectors: ["Chemical", "Food Processing", "Textile & Apparel"],
    tag: "Circular Economy",
    tagColour: "teal",
    highlight: "Resource-efficiency for high-waste sectors",
    description: "Circular economy and sustainable resource-efficiency financing for waste-intensive sectors",
    requirements: [
      "GreenScore ≥ 55",
      "Sectors: Chemical, Food Processing, Textile & Apparel",
      "Projects focusing on resource recovery & recycling"
    ],
    applyUrl: "https://onlineloanappl.sidbi.in/OnlineApplication/",
    apply_url: "https://onlineloanappl.sidbi.in/OnlineApplication/",
    infoUrl: "https://www.sidbi.in/en/pages/incentive-schemes-for-green-loans",
    info_url: "https://www.sidbi.in/en/pages/incentive-schemes-for-green-loans",
    sourceLabel: "SIDBI Green Loan Incentives Page",
  },
  {
    id: "ireda-solar",
    bank: "IREDA",
    bankLogo: "☀️",
    scheme: "Solar Energy Financing",
    minScore: 65,
    min_score: 65,
    maxAmountCr: 15,
    max_amount_cr: 15,
    rateMin: 9.5,
    rate_min: 9.5,
    rateMax: 10.5,
    rate_max: 10.5,
    tenureYears: 18,
    tenure_yr: 18,
    eligibleSectors: null,
    eligible_sectors: null,
    tag: "MNRE Subsidised",
    tagColour: "yellow",
    highlight: "Rooftop and ground solar",
    description: "Rooftop and ground-mount solar financing for industrial and commercial MSME consumers",
    requirements: [
      "GreenScore ≥ 65",
      "All sectors eligible for RE projects",
      "Feasibility report & grid layout DPR",
      "IREDA portal registration"
    ],
    applyUrl: "https://iredacustomer.powerappsportals.com/",
    apply_url: "https://iredacustomer.powerappsportals.com/",
    infoUrl: "https://www.ireda.in/solar-energy",
    info_url: "https://www.ireda.in/solar-energy",
    sourceLabel: "IREDA Solar Scheme",
  },
  {
    id: "ireda-wind",
    bank: "IREDA",
    bankLogo: "💨",
    scheme: "Wind Energy Financing",
    minScore: 65,
    min_score: 65,
    maxAmountCr: 20,
    max_amount_cr: 20,
    rateMin: 9.5,
    rate_min: 9.5,
    rateMax: 10.5,
    rate_max: 10.5,
    tenureYears: 15,
    tenure_yr: 15,
    eligibleSectors: ["Logistics", "Chemical", "Auto Parts", "Textile & Apparel"],
    eligible_sectors: ["Logistics", "Chemical", "Auto Parts", "Textile & Apparel"],
    tag: "MNRE Subsidised",
    tagColour: "blue",
    highlight: "Wind projects for industrial consumers",
    description: "Wind energy project financing for high-energy industrial consumers",
    requirements: [
      "GreenScore ≥ 65",
      "Sectors: Logistics, Chemical, Auto Parts, Textile & Apparel",
      "Suitable wind data / site allocation"
    ],
    applyUrl: "https://iredacustomer.powerappsportals.com/",
    apply_url: "https://iredacustomer.powerappsportals.com/",
    infoUrl: "https://www.ireda.in/wind-energy",
    info_url: "https://www.ireda.in/wind-energy",
    sourceLabel: "IREDA Wind Scheme",
  },
  {
    id: "ireda-bio",
    bank: "IREDA",
    bankLogo: "🔥",
    scheme: "Bio Energy Financing",
    minScore: 60,
    min_score: 60,
    maxAmountCr: 10,
    max_amount_cr: 10,
    rateMin: 9.5,
    rate_min: 9.5,
    rateMax: 11.0,
    rate_max: 11.0,
    tenureYears: 12,
    tenure_yr: 12,
    eligibleSectors: ["Food Processing", "Chemical"],
    eligible_sectors: ["Food Processing", "Chemical"],
    tag: "Waste to Energy",
    tagColour: "orange",
    highlight: "Biogas, biomass, and waste-to-energy",
    description: "Biogas, biomass and waste-to-energy project financing for organic waste-intensive sectors",
    requirements: [
      "GreenScore ≥ 60",
      "Sectors: Food Processing, Chemical",
      "Stable organic waste / biomass feed contract"
    ],
    applyUrl: "https://iredacustomer.powerappsportals.com/",
    apply_url: "https://iredacustomer.powerappsportals.com/",
    infoUrl: "https://www.ireda.in/bio-energy",
    info_url: "https://www.ireda.in/bio-energy",
    sourceLabel: "IREDA Bio-Energy Scheme",
  },
  {
    id: "sbi-green",
    bank: "State Bank of India",
    bankLogo: "🏦",
    scheme: "SBI Green Finance",
    minScore: 50,
    min_score: 50,
    maxAmountCr: 10,
    max_amount_cr: 10,
    rateMin: 8.5,
    rate_min: 8.5,
    rateMax: 10.5,
    rate_max: 10.5,
    tenureYears: 10,
    tenure_yr: 10,
    eligibleSectors: null,
    eligible_sectors: null,
    tag: "PSL Green",
    tagColour: "emerald",
    highlight: "Climate & sustainable finance",
    description: "Climate financing for renewable energy and sustainable projects under SBI Green portal",
    requirements: [
      "GreenScore ≥ 50",
      "All sectors eligible",
      "SBI banking account relationship preferred"
    ],
    applyUrl: "https://sbi.bank.in/web/sbi-green",
    apply_url: "https://sbi.bank.in/web/sbi-green",
    infoUrl: "https://sbi.bank.in/web/sbi-green",
    info_url: "https://sbi.bank.in/web/sbi-green",
    sourceLabel: "SBI Green Portal",
  },
  {
    id: "sbi-solar-vendor",
    bank: "State Bank of India",
    bankLogo: "☀️",
    scheme: "SBI Solar Vendor Finance",
    minScore: 50,
    min_score: 50,
    maxAmountCr: 5,
    max_amount_cr: 5,
    rateMin: 8.5,
    rate_min: 8.5,
    rateMax: 10.0,
    rate_max: 10.0,
    tenureYears: 7,
    tenure_yr: 7,
    eligibleSectors: ["Textile & Apparel", "Auto Parts", "Food Processing", "Chemical"],
    eligible_sectors: ["Textile & Apparel", "Auto Parts", "Food Processing", "Chemical"],
    tag: "No Collateral · CGTMSE",
    tagColour: "yellow",
    highlight: "Collateral-free rooftop solar",
    description: "Collateral-free rooftop solar financing for MSME businesses up to ₹5 Cr. CGTMSE covered.",
    requirements: [
      "GreenScore ≥ 50",
      "Sectors: Textile & Apparel, Auto Parts, Food Processing, Chemical",
      "Minimum CIBIL 650",
      "MNRE-registered solar vendors only"
    ],
    applyUrl: "https://sbi.bank.in/web/sbi-green/green-loans/business/finance-to-solar-vendors",
    apply_url: "https://sbi.bank.in/web/sbi-green/green-loans/business/finance-to-solar-vendors",
    infoUrl: "https://sbi.bank.in/web/sbi-green/green-loans/business/finance-to-solar-vendors",
    info_url: "https://sbi.bank.in/web/sbi-green/green-loans/business/finance-to-solar-vendors",
    sourceLabel: "SBI Solar Vendor Finance Page",
  },
  {
    id: "sbi-energy-efficient",
    bank: "State Bank of India",
    bankLogo: "⚡",
    scheme: "SBI Energy Efficient Products",
    minScore: 45,
    min_score: 45,
    maxAmountCr: 10,
    max_amount_cr: 10,
    rateMin: 9.0,
    rate_min: 9.0,
    rateMax: 11.0,
    rate_max: 11.0,
    tenureYears: 7,
    tenure_yr: 7,
    eligibleSectors: ["Auto Parts", "Chemical", "Textile & Apparel", "Food Processing"],
    eligible_sectors: ["Auto Parts", "Chemical", "Textile & Apparel", "Food Processing"],
    tag: "MSME Equipment",
    tagColour: "indigo",
    highlight: "Machinery and equipment upgrade",
    description: "Financing for energy-efficient machinery and equipment upgrades for MSME businesses",
    requirements: [
      "GreenScore ≥ 45",
      "Sectors: Auto Parts, Chemical, Textile & Apparel, Food Processing",
      "Quotation / specifications for upgrades"
    ],
    applyUrl: "https://bank.sbi/web/business/sme/sme-loans/energy-efficient-products",
    apply_url: "https://bank.sbi/web/business/sme/sme-loans/energy-efficient-products",
    infoUrl: "https://bank.sbi/web/business/sme/sme-loans/energy-efficient-products",
    info_url: "https://bank.sbi/web/business/sme/sme-loans/energy-efficient-products",
    sourceLabel: "SBI MSME SME Loans Page",
  },
  {
    id: "nabard-ccf",
    bank: "NABARD",
    bankLogo: "🌳",
    scheme: "Climate Change Fund (CCF)",
    minScore: 55,
    min_score: 55,
    maxAmountCr: 3,
    max_amount_cr: 3,
    rateMin: 8.0,
    rate_min: 8.0,
    rateMax: 9.2,
    rate_max: 9.2,
    tenureYears: 7,
    tenure_yr: 7,
    eligibleSectors: ["Food Processing", "Logistics", "Chemical"],
    eligible_sectors: ["Food Processing", "Logistics", "Chemical"],
    tag: "Circular Economy",
    tagColour: "teal",
    highlight: "Mitigation & adaptation projects",
    description: "Climate adaptation and mitigation projects for food processing, logistics and chemical MSMEs",
    requirements: [
      "GreenScore ≥ 55",
      "Sectors: Food Processing, Logistics, Chemical",
      "Project must show rural linkage or supply chain footprint"
    ],
    applyUrl: "https://www.nabard.org/about-departments.aspx?id=5&cid=2788",
    apply_url: "https://www.nabard.org/about-departments.aspx?id=5&cid=2788",
    infoUrl: "https://www.nabard.org/about-departments.aspx?id=5&cid=2788",
    info_url: "https://www.nabard.org/about-departments.aspx?id=5&cid=2788",
    sourceLabel: "NABARD Climate Change Department",
  },
  {
    id: "nabard-nglf",
    bank: "NABARD",
    bankLogo: "🌿",
    scheme: "National Green Lending Facility",
    minScore: 55,
    min_score: 55,
    maxAmountCr: 5,
    max_amount_cr: 5,
    rateMin: 8.0,
    rate_min: 8.0,
    rateMax: 9.5,
    rate_max: 9.5,
    tenureYears: 10,
    tenure_yr: 10,
    eligibleSectors: ["Food Processing", "Logistics", "Textile & Apparel"],
    eligible_sectors: ["Food Processing", "Logistics", "Textile & Apparel"],
    tag: "Green Infrastructure",
    tagColour: "emerald",
    highlight: "Funding up to 85% project cost",
    description: "Up to 85% project cost funding for green impact projects in rural-linked sectors",
    requirements: [
      "GreenScore ≥ 55",
      "Sectors: Food Processing, Logistics, Textile & Apparel",
      "Commercial entity or cooperative status"
    ],
    applyUrl: "https://www.nabard.org/about-departments.aspx?id=5&cid=2788",
    apply_url: "https://www.nabard.org/about-departments.aspx?id=5&cid=2788",
    infoUrl: "https://www.nabard.org/about-departments.aspx?id=5&cid=2788",
    info_url: "https://www.nabard.org/about-departments.aspx?id=5&cid=2788",
    sourceLabel: "NABARD Climate Change Department",
  },
  {
    id: "hdfc-sustainable",
    bank: "HDFC Bank",
    bankLogo: "💧",
    scheme: "Sustainable Finance (ESG-linked)",
    minScore: 50,
    min_score: 50,
    maxAmountCr: 4,
    max_amount_cr: 4,
    rateMin: 8.5,
    rate_min: 8.5,
    rateMax: 10.5,
    rate_max: 10.5,
    tenureYears: 5,
    tenure_yr: 5,
    eligibleSectors: null,
    eligible_sectors: null,
    tag: "Water Resilience",
    tagColour: "blue",
    highlight: "ESG-linked business lending",
    description: "ESG-linked MSME loans under HDFC Bank's Sustainalytics-rated Sustainable Finance Framework",
    requirements: [
      "GreenScore ≥ 50",
      "All sectors eligible",
      "Adherence to ESG compliance checklist"
    ],
    applyUrl: "https://www.hdfcbank.com/sme/borrow/msme-loan",
    apply_url: "https://www.hdfcbank.com/sme/borrow/msme-loan",
    infoUrl: "https://www.hdfcbank.com/sme/borrow/msme-loan",
    info_url: "https://www.hdfcbank.com/sme/borrow/msme-loan",
    sourceLabel: "HDFC Bank SME MSME Loans",
  },
];

