export interface LoanScheme {
  id: string;
  bank: string;
  bankLogo: string;
  scheme: string;
  minScore: number;
  maxAmountCr: number;
  rateMin: number;
  rateMax: number;
  tenureYears: number;
  eligibleSectors: string[] | null;
  tag: string;
  tagColour: string;
  highlight: string;
  description: string;
  requirements: string[];
  applyUrl: string;
  sourceLabel: string;
}

export const LOAN_SCHEMES: LoanScheme[] = [
  // General Loans
  {
    id: 'sidbi-green',
    bank: 'SIDBI',
    bankLogo: '🏦',
    scheme: 'Green Finance Scheme',
    minScore: 55,
    maxAmountCr: 5,
    rateMin: 8.0,
    rateMax: 9.5,
    tenureYears: 7,
    eligibleSectors: null,
    tag: 'RBI Priority Sector',
    tagColour: 'emerald',
    highlight: 'Lowest rate for high scorers',
    description: 'For SMEs investing in energy efficiency, clean technology, or renewable energy adoption.',
    requirements: ['GreenScore ≥ 55', 'Audited financials for 2 years', 'MSME registration (Udyam)', 'Environmental investment plan'],
    applyUrl: 'https://www.sidbi.in/en/products/green-finance',
    sourceLabel: 'SIDBI Official Scheme Page',
  },
  {
    id: 'hdfc-esgl',
    bank: 'HDFC Bank',
    bankLogo: '🏛️',
    scheme: 'ESG-Linked SME Loan',
    minScore: 65,
    maxAmountCr: 3,
    rateMin: 9.0,
    rateMax: 11.0,
    tenureYears: 7,
    eligibleSectors: null,
    tag: 'ESG-Linked Rate',
    tagColour: 'blue',
    highlight: 'Rate improves as your GreenScore improves',
    description: 'Interest rate is adjusted annually based on GreenScore changes. Improve your score by 5+ points and get a 0.25% rate reduction next year.',
    requirements: ['GreenScore ≥ 65', 'Annual GreenScore recertification', 'HDFC Bank current account', 'GST returns for 2 years'],
    applyUrl: 'https://www.hdfcbank.com/sme/loans/working-capital-loans',
    sourceLabel: 'HDFC Bank SME Loans',
  },
  {
    id: 'bob-green',
    bank: 'Bank of Baroda',
    bankLogo: '🏦',
    scheme: 'Baroda Green Loan',
    minScore: 45,
    maxAmountCr: 2,
    rateMin: 9.5,
    rateMax: 12.0,
    tenureYears: 5,
    eligibleSectors: null,
    tag: 'Entry Level Green',
    tagColour: 'orange',
    highlight: 'Most accessible — lowest score threshold',
    description: 'Entry-level green financing for SMEs beginning their sustainability journey.',
    requirements: ['GreenScore ≥ 45', 'Business vintage > 3 years', 'No NPA history', 'Green investment commitment letter'],
    applyUrl: 'https://www.bankofbaroda.in/msme/loans-and-advances',
    sourceLabel: 'Bank of Baroda MSME',
  },
  // Textile Specific
  {
    id: 'hdfc-textile-water',
    bank: 'HDFC Bank',
    bankLogo: '💧',
    scheme: 'Water Efficiency Finance',
    minScore: 60,
    maxAmountCr: 4,
    rateMin: 8.5,
    rateMax: 10.0,
    tenureYears: 5,
    eligibleSectors: ['Textile', 'Textile & Apparel'],
    tag: 'Water Resilience',
    tagColour: 'blue',
    highlight: 'Fund zero liquid discharge (ZLD) systems',
    description: 'Specialized loan for textile manufacturers upgrading to water-efficient dyeing processes and wastewater recycling.',
    requirements: ['GreenScore ≥ 60', 'High baseline water usage', 'Implementation of ZLD or ETP'],
    applyUrl: 'https://www.hdfcbank.com',
    sourceLabel: 'HDFC Sustainable Finance',
  },
  {
    id: 'icici-sustainable-dye',
    bank: 'ICICI Bank',
    bankLogo: '🎨',
    scheme: 'Sustainable Dye Transition Loan',
    minScore: 50,
    maxAmountCr: 2,
    rateMin: 8.8,
    rateMax: 10.5,
    tenureYears: 4,
    eligibleSectors: ['Textile', 'Textile & Apparel'],
    tag: 'Chemical Safety',
    tagColour: 'teal',
    highlight: 'Subsidized rates for non-toxic dye adoption',
    description: 'Financing intended to cover the capital expenditure of transitioning to natural or low-impact synthetic dyes.',
    requirements: ['GreenScore ≥ 50', 'Textile manufacturing license', 'Transition roadmap'],
    applyUrl: 'https://www.icicibank.com',
    sourceLabel: 'ICICI SME Finance',
  },
  // Logistics Specific
  {
    id: 'tata-ev-fleet',
    bank: 'Tata Capital',
    bankLogo: '🚚',
    scheme: 'EV Fleet Financing',
    minScore: 55,
    maxAmountCr: 10,
    rateMin: 7.5,
    rateMax: 8.9,
    tenureYears: 8,
    eligibleSectors: ['Logistics', 'Transportation'],
    tag: 'E-Mobility',
    tagColour: 'emerald',
    highlight: 'Lowest rates for electric commercial vehicles',
    description: 'Aggressive rate cuts for replacing diesel fleets with electric commercial vehicles and installing charging infrastructure.',
    requirements: ['GreenScore ≥ 55', 'Fleet size > 10 vehicles', 'OEM partnership agreement'],
    applyUrl: 'https://www.tatacapital.com',
    sourceLabel: 'Tata Capital Cleantech',
  },
  {
    id: 'sbi-fuel-opt',
    bank: 'State Bank of India',
    bankLogo: '⛽',
    scheme: 'Fuel Optimization Tech Loan',
    minScore: 50,
    maxAmountCr: 1.5,
    rateMin: 9.0,
    rateMax: 10.5,
    tenureYears: 3,
    eligibleSectors: ['Logistics', 'Transportation'],
    tag: 'Efficiency Tech',
    tagColour: 'indigo',
    highlight: 'Quick approval for telematics & aerodynamics',
    description: 'Short-term financing for logistics companies investing in route optimization software, telematics, and aerodynamic truck modifications.',
    requirements: ['GreenScore ≥ 50', 'Logistics operator license'],
    applyUrl: 'https://sbi.co.in',
    sourceLabel: 'SBI SME',
  },
  // Manufacturing Specific
  {
    id: 'ireda-solar',
    bank: 'IREDA',
    bankLogo: '☀️',
    scheme: 'Industrial Solar Integration Finance',
    minScore: 70,
    maxAmountCr: 15,
    rateMin: 7.2,
    rateMax: 8.5,
    tenureYears: 10,
    eligibleSectors: ['Manufacturing', 'Auto Parts', 'Chemical'],
    tag: 'MNRE Subsidized',
    tagColour: 'yellow',
    highlight: 'Massive limit for rooftop/ground-mount solar',
    description: 'Dedicated financing for large-scale solar installations by heavy manufacturing MSMEs. Administered by India Renewable Energy Development Agency.',
    requirements: ['GreenScore ≥ 70', 'Renewable energy project DPR', 'Techno-economic feasibility report'],
    applyUrl: 'https://www.ireda.in',
    sourceLabel: 'IREDA MSME Scheme',
  },
  {
    id: 'sidbi-energy-opt',
    bank: 'SIDBI',
    bankLogo: '⚡',
    scheme: 'Energy Optimization Loan',
    minScore: 60,
    maxAmountCr: 5,
    rateMin: 8.2,
    rateMax: 9.5,
    tenureYears: 6,
    eligibleSectors: ['Manufacturing', 'Auto Parts', 'Chemical'],
    tag: 'Energy Efficiency',
    tagColour: 'purple',
    highlight: 'Fund VFDs, efficient motors, and HVAC upgrades',
    description: 'Financing for replacing legacy industrial equipment with BEE-star rated energy-efficient machinery.',
    requirements: ['GreenScore ≥ 60', 'Energy audit report (BEE empanelled auditor)'],
    applyUrl: 'https://www.sidbi.in',
    sourceLabel: 'SIDBI Energy Efficiency',
  },
  // Food Processing Specific
  {
    id: 'nabard-waste',
    bank: 'NABARD',
    bankLogo: '♻️',
    scheme: 'Waste-to-Wealth Finance',
    minScore: 58,
    maxAmountCr: 3,
    rateMin: 8.0,
    rateMax: 9.2,
    tenureYears: 7,
    eligibleSectors: ['Food Processing', 'Agri-Business'],
    tag: 'Circular Economy',
    tagColour: 'teal',
    highlight: 'Convert food waste into biogas or compost',
    description: 'Fund the installation of biomethanation plants or industrial composting facilities to manage organic waste effectively.',
    requirements: ['GreenScore ≥ 58', 'FSSAI License', 'Waste generation baseline'],
    applyUrl: 'https://www.nabard.org',
    sourceLabel: 'NABARD Agri-Innovation',
  },
  {
    id: 'yes-sustainable-pack',
    bank: 'Yes Bank',
    bankLogo: '📦',
    scheme: 'Sustainable Packaging Transition',
    minScore: 55,
    maxAmountCr: 2,
    rateMin: 8.5,
    rateMax: 10.0,
    tenureYears: 4,
    eligibleSectors: ['Food Processing', 'FMCG'],
    tag: 'Plastic Reduction',
    tagColour: 'emerald',
    highlight: 'Switch to biodegradable or recyclable materials',
    description: 'Working capital and capex loans to help food brands transition away from single-use plastics to sustainable packaging alternatives.',
    requirements: ['GreenScore ≥ 55', 'EPR compliance certificate'],
    applyUrl: 'https://www.yesbank.in',
    sourceLabel: 'Yes Bank Sustainable MSME',
  },
  // Retail Specific
  {
    id: 'axis-sustainable-retail',
    bank: 'Axis Bank',
    bankLogo: '🏪',
    scheme: 'Sustainable Store Operations Loan',
    minScore: 50,
    maxAmountCr: 1.5,
    rateMin: 8.8,
    rateMax: 10.5,
    tenureYears: 5,
    eligibleSectors: ['Retail', 'E-commerce'],
    tag: 'Green Retail',
    tagColour: 'blue',
    highlight: 'Upgrade store lighting, HVAC, and refrigeration',
    description: 'Financing for retail chains and standalone stores to upgrade to LED lighting, energy-efficient HVAC, and smart refrigeration systems.',
    requirements: ['GreenScore ≥ 50', 'Minimum 3 operating storefronts'],
    applyUrl: 'https://www.axisbank.com',
    sourceLabel: 'Axis SME Loans',
  }
];
