INSERT INTO loan_offers (bank_name, product_name, min_score, max_amount_cr, interest_rate_min, interest_rate_max, tenure_years, eligible_sectors, rbi_scheme, description, apply_url, info_url) VALUES
  ('SIDBI', 'Green Finance Scheme (GFS)', 55, 5.00, 8.00, 9.50, 7, NULL, 'RBI Priority Sector', 'Financing for renewable energy, energy efficiency, EVs, waste management, green manufacturing', 'https://onlineloanappl.sidbi.in/OnlineApplication/', 'https://www.sidbi.in/en/green-finance'),
  ('SIDBI', '4E Scheme (End-to-End Energy Efficiency)', 55, 3.00, 7.50, 9.00, 5, ARRAY['Textile & Apparel', 'Auto Parts', 'Chemical', 'Food Processing'], 'Energy Efficiency', 'MSME energy-efficiency machinery upgrades and sustainable equipment financing', 'https://onlineloanappl.sidbi.in/OnlineApplication/', 'https://www.sidbi.in/en/green-finance'),
  ('SIDBI', 'MSE-GIFT Scheme', 50, 2.00, 7.00, 8.50, 5, NULL, 'World Bank RAMP', 'Concessional green technology adoption financing for MSMEs under World Bank RAMP Programme', 'https://onlineloanappl.sidbi.in/OnlineApplication/', 'https://www.sidbi.in/en/pages/incentive-schemes-for-green-loans'),
  ('SIDBI', 'MSE-SPICE Scheme', 55, 2.00, 7.50, 9.00, 5, ARRAY['Chemical', 'Food Processing', 'Textile & Apparel'], 'Circular Economy', 'Circular economy and sustainable resource-efficiency financing for waste-intensive sectors', 'https://onlineloanappl.sidbi.in/OnlineApplication/', 'https://www.sidbi.in/en/pages/incentive-schemes-for-green-loans'),
  ('IREDA', 'Solar Energy Financing', 65, 15.00, 9.50, 10.50, 18, NULL, 'MNRE Subsidised', 'Rooftop and ground-mount solar financing for industrial and commercial MSME consumers', 'https://iredacustomer.powerappsportals.com/', 'https://www.ireda.in/solar-energy'),
  ('IREDA', 'Wind Energy Financing', 65, 20.00, 9.50, 10.50, 15, ARRAY['Logistics', 'Chemical', 'Auto Parts', 'Textile & Apparel'], 'MNRE Subsidised', 'Wind energy project financing for high-energy industrial consumers', 'https://iredacustomer.powerappsportals.com/', 'https://www.ireda.in/wind-energy'),
  ('IREDA', 'Bio Energy Financing', 60, 10.00, 9.50, 11.00, 12, ARRAY['Food Processing', 'Chemical'], 'Waste to Energy', 'Biogas, biomass and waste-to-energy project financing for organic waste-intensive sectors', 'https://iredacustomer.powerappsportals.com/', 'https://www.ireda.in/bio-energy'),
  ('State Bank of India', 'SBI Green Finance', 50, 10.00, 8.50, 10.50, 10, NULL, 'PSL Green', 'Climate financing for renewable energy and sustainable projects under SBI Green portal', 'https://sbi.bank.in/web/sbi-green', 'https://sbi.bank.in/web/sbi-green'),
  ('State Bank of India', 'SBI Solar Vendor Finance', 50, 5.00, 8.50, 10.00, 7, ARRAY['Textile & Apparel', 'Auto Parts', 'Food Processing', 'Chemical'], 'No Collateral · CGTMSE', 'Collateral-free rooftop solar financing for MSME businesses up to ₹5 Cr. CGTMSE covered.', 'https://sbi.bank.in/web/sbi-green/green-loans/business/finance-to-solar-vendors', 'https://sbi.bank.in/web/sbi-green/green-loans/business/finance-to-solar-vendors'),
  ('State Bank of India', 'SBI Energy Efficient Products', 45, 10.00, 9.00, 11.00, 7, ARRAY['Auto Parts', 'Chemical', 'Textile & Apparel', 'Food Processing'], 'MSME Equipment', 'Financing for energy-efficient machinery and equipment upgrades for MSME businesses', 'https://bank.sbi/web/business/sme/sme-loans/energy-efficient-products', 'https://bank.sbi/web/business/sme/sme-loans/energy-efficient-products'),
  ('NABARD', 'Climate Change Fund (CCF)', 55, 3.00, 8.00, 9.20, 7, ARRAY['Food Processing', 'Logistics', 'Chemical'], 'Circular Economy', 'Climate adaptation and mitigation projects for food processing, logistics and chemical MSMEs', 'https://www.nabard.org/about-departments.aspx?id=5&cid=2788', 'https://www.nabard.org/about-departments.aspx?id=5&cid=2788'),
  ('NABARD', 'National Green Lending Facility', 55, 5.00, 8.00, 9.50, 10, ARRAY['Food Processing', 'Logistics', 'Textile & Apparel'], 'Green Infrastructure', 'Up to 85% project cost funding for green impact projects in rural-linked sectors', 'https://www.nabard.org/about-departments.aspx?id=5&cid=2788', 'https://www.nabard.org/about-departments.aspx?id=5&cid=2788'),
  ('HDFC Bank', 'Sustainable Finance (ESG-linked)', 50, 4.00, 8.50, 10.50, 5, NULL, 'Water Resilience', 'ESG-linked MSME loans under HDFC Bank''s Sustainalytics-rated Sustainable Finance Framework', 'https://www.hdfcbank.com/sme/borrow/msme-loan', 'https://www.hdfcbank.com/sme/borrow/msme-loan');

INSERT INTO sector_benchmarks (id, sector, avg_electricity_mwh_per_cr, avg_diesel_litres_per_cr, avg_water_kl_per_cr, avg_waste_t_per_cr, avg_renewable_pct, avg_greenscore) VALUES
  (gen_random_uuid(), 'Textile & Apparel', 45.0, 120.0, 1400.0, 2.2, 5.0, 55.6),
  (gen_random_uuid(), 'Food Processing', 50.0, 150.0, 700.0, 1.5, 6.0, 55.6),
  (gen_random_uuid(), 'Auto Parts', 60.0, 200.0, 800.0, 2.2, 8.0, 55.6),
  (gen_random_uuid(), 'Logistics', 10.0, 4000.0, 200.0, 0.5, 4.0, 55.6),
  (gen_random_uuid(), 'IT Services', 15.0, 50.0, 140.0, 0.22, 10.0, 55.6),
  (gen_random_uuid(), 'Chemical', 70.0, 800.0, 3000.0, 4.5, 8.0, 55.6);

